spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          # Discovery Server Route
          - id: messenger-server
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          # Discovery Server Static Resources Route
          - id: messenger-server-static
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt_secret: ${JWT_SECRET}